CMAKE_MINIMUM_REQUIRED(VERSION 3.28)

SET(TESTS tests)

PROJECT(c-unit-tests LANGUAGES C)

# Find all test source files
FILE(GLOB TEST_SOURCES CONFIGURE_DEPENDS
    "src/tests/*.c"
)

MESSAGE(STATUS "C-UNIT-TESTS SOURCE DIR: ${CMAKE_CURRENT_SOURCE_DIR}")
MESSAGE(STATUS "C-UNIT-TESTS BINARY DIR: ${CMAKE_CURRENT_BINARY_DIR}")
MESSAGE(STATUS "TEST_SOURCES: ${TEST_SOURCES}")

# The test files
FOREACH(TEST_SOURCE ${TEST_SOURCES})
    GET_FILENAME_COMPONENT(TEST_NAME ${TEST_SOURCE} NAME_WE)

    ADD_LIBRARY(${TEST_NAME} SHARED ${TEST_SOURCE})
    TARGET_LINK_LIBRARIES(${TEST_NAME} PRIVATE wolfhound)
    SET_TARGET_PROPERTIES(${TEST_NAME} PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/src/c-unit-tests/tests")
ENDFOREACH()

# The binary
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
ADD_EXECUTABLE(c-unit-tests "src/source.c")
TARGET_LINK_LIBRARIES(c-unit-tests PRIVATE wolfhound)
