CMAKE_MINIMUM_REQUIRED(VERSION 3.28)
PROJECT(editor LANGUAGES C) #Fortran)

#iF (WIN32)
#	ADD_SUBDIRECTORY("../..")
#	INCLUDE_DIRECTORIES("../../include")
#ELSE()
#	ADD_SUBDIRECTORY(engine)
#	INCLUDE_DIRECTORIES("engine/include")
#ENDIF()

CONFIGURE_FILE(${CMAKE_CURRENT_SOURCE_DIR}/config.lua ${CMAKE_CURRENT_BINARY_DIR}/config.lua COPYONLY)
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")

ADD_EXECUTABLE(chess "src/source.c")
TARGET_LINK_LIBRARIES(chess PRIVATE wolfhound)
