! core.f95

MODULE WOLFHOUND_FORTRAN_MATHS
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE

CONTAINS

  FUNCTION WOLFHOUND_INTEGER_LOG(IN_BASE, IN_X) BIND (C, NAME="_wh_fortran_intlog64") RESULT(R)
    INTEGER(KIND = C_INT64_T), VALUE :: IN_BASE
    INTEGER(KIND = C_INT64_T), VALUE :: IN_X
    INTEGER(KIND = C_INT64_T) :: R

    INTEGER(KIND = C_INT64_T) :: X
    INTEGER(KIND = C_INT64_T) :: BASE

    BASE = IN_BASE
    X = ABS(IN_X)
    R = 0

    IF (2 .GE. BASE) THEN
      BASE = 10
    ENDIF

    DO WHILE (X >= BASE)
      X = X / BASE
      R = R + 1
    END DO
  END FUNCTION

  FUNCTION WOLFHOUND_INTEGER_POWER(POWER, X) BIND (C, NAME="_wh_fortran_intpow64") RESULT(R)
    INTEGER(KIND = C_INT64_T), VALUE :: POWER
    INTEGER(KIND = C_INT64_T), VALUE :: X
    INTEGER(KIND = C_INT64_T) :: R

    R = 1

    IF (0 /= X) THEN
      R = POWER
      X = X - 1

      DO WHILE(0 /= X)
        R = R * POWER
        X = X - 1
      END DO
    END IF
  END FUNCTION WOLFHOUND_INTEGER_POWER

END MODULE WOLFHOUND_FORTRAN_MATHS
