! core.f95

MODULE WOLFHOUND_FORTRAN_MATHS
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE

CONTAINS

  FUNCTION WOLFHOUND_INTEGER_DEC_COUNT(BASE, X) BIND (C, NAME="_wh_fortran_dec_count") RESULT(R)
    INTEGER(KIND = C_INT64_T), VALUE :: BASE
    INTEGER(KIND = C_INT64_T), VALUE :: X
    INTEGER(KIND = C_INT64_T) :: R

    X = ABS(X)
    R = 0

    IF (2 > BASE) THEN
      BASE = 10
    ENDIF

    DO WHILE (X >= BASE)
      X = X / BASE
      R = R + 1
    END DO
  END FUNCTION

  FUNCTION WOLFHOUND_INTEGER_POWER(POWER, TIMES) BIND (C, NAME="_wh_fortran_intpow64") RESULT(R)
    INTEGER(KIND = C_INT64_T), VALUE :: POWER
    INTEGER(KIND = C_INT64_T), VALUE :: TIMES
    INTEGER(KIND = C_INT64_T) :: R

    R = 1

    IF (0 /= TIMES) THEN
      R = POWER
      TIMES = TIMES - 1

      DO WHILE(0 /= TIMES)
        R = R * POWER
        TIMES = TIMES - 1
      END DO
    END IF
  END FUNCTION WOLFHOUND_INTEGER_POWER

END MODULE WOLFHOUND_FORTRAN_MATHS
