INCLUDE(CheckLanguage)

# Telling CMake that we use C and Fortran, Nasm
# Adding Fortran Support
CHECK_LANGUAGE(Fortran)
CHECK_LANGUAGE(ASM_NASM)

# Lets use the new C++ as well
IF (NO_CXX_COMPILER)
	SET(CXX_ENABLED FALSE)
ELSE()
	MESSAGE("${LOG_PREFIX} C++ is enabled")

	SET(CXX_ENABLED TRUE)
	SET(CMAKE_CXX_STANDARD_REQUIRED ON)
ENDIF()

IF(CMAKE_ASM_NASM_COMPILER AND NOT CMAKE_ASM_NASM_COMPILER MATCHES "-NOTFOUND")
	MESSAGE("${LOG_PREFIX} NASM found: ${CMAKE_ASM_NASM_COMPILER}")
	SET(NASM_ENABLED TRUE)
ELSE()
	MESSAGE(STATUS "${LOG_PREFIX} NASM not found")
	SET(NASM_ENABLED FALSE)
ENDIF()
