INCLUDE(CheckIncludeFile)

SET(LIBRARY_NAME glew GLEW glew32 glew32s)

CHECK_INCLUDE_FILE("GL/glew.h" HAVE_GLEW_HEADER)

IF(NOT HAVE_GLEW_HEADER)
	MESSAGE(WARNING "GLEW header not found. GLEW features will be disabled.")
	ADD_COMPILE_DEFINITIONS(WH_GLEW_NOT_FOUND=1)
ELSE()
	MESSAGE("GLEW headers found!")

	FIND_LIBRARY(LIB_GLEW
		NAMES ${LIBRARY_NAME}
		PATH_SUFFIXES Lib lib
	)

	IF(NOT LIB_GLEW)
		# TODO download

		FIND_LIBRARY(LIB_GLEW
			NAMES ${LIBRARY_NAME}
		)
	ENDIF()

	IF(NOT LIB_GLEW)
		MESSAGE(WARNING "GLEW library not found. GLEW features will be disabled.")
		ADD_COMPILE_DEFINITIONS(WH_UNWIND_NOT_FOUND=1)
	ELSE()
		TARGET_LINK_LIBRARIES(${APP_NAME} INTERFACE ${LIB_GLEW})
	ENDIF()
ENDIF()

