#INCLUDE(${CMAKE_CURRENT_LIST_DIR}/find.cmake)

#SET(LIB_NAME_ALTS glfw glfw3 GLFW3)
#SET(LIB_HEADER_NAMES glfw.h glfw/glfw3.h GLFW/glfw3.h)
#SET(LIB_NAME_ALTS glfw glfw3 glfw3dll GLFW GLFW3)

#WH_FIND_LIB(glfw)

WH_FIND_V2(
	"glfw"
	"glfw;glfw3;GLFW3"
	"glfw.h;glfw3.h;glfw3.h"
	"GLFW;glfw"
	FALSE 
	WH_GLFW_LIB 
	WH_GLFW_INC
)

IF(WH_GLFW_LIB)
	LIST(APPEND WH_LIBS ${WH_GLFW_LIB})
	LIST(APPEND WH_INCLUDES ${WH_GLFW_INC})
	LIST(APPEND GLFW_SOURCES ${C_SOURCES})
ELSE()
	LIST(APPEND WH_DEFS "WH_GLFW_NOT_FOUND")
ENDIF()
