
FUNCTION(WH_FIND_LIB LIB_NAME)
	FIND_PACKAGE(${LIB_NAME} QUIET)
	STRING(TOUPPER ${LIB_NAME} UPPER_LIB_NAME)

	IF (${${UPPER_LIB_NAME}_DISABLED})
		MESSAGE("${LOG_PREFIX} ${LIB_NAME} library disabled by user. ${LIB_NAME} features will be disabled.")
		LIST(APPEND WH_DEFS WH_${UPPER_LIB_NAME}_NOT_FOUND)
	ELSEIF(${LIB_NAME}_FOUND)
		MESSAGE("${LOG_PREFIX} Found ${LIB_NAME} (Version ${${UPPER_LIB_NAME}_VERSION})")
		LIST(APPEND C_SOURCES ${${UPPER_LIB_NAME}_SOURCES})

		IF(TARGET ${LIB_NAME}::${LIB_NAME})
			LIST(APPEND WH_LIBS ${LIB_NAME}::${LIB_NAME})
		ELSE()
			LIST(APPEND WH_LIBS ${${UPPER_LIB_NAME}_LIBRARIES})
			LIST(APPEND WH_INCLUDES ${${UPPER_LIB_NAME}_INCLUDE_DIRS})
		ENDIF()
	ELSE()
		MESSAGE("${LOG_PREFIX} Did not find pakage [ ${LIB_NAME} ] doing it old school.")

		FIND_PATH(INC_DIR
				NAMES ${LIB_HEADER_NAMES}
				PATH_SUFFIXES ${INCLUDE_PREFIX} include/Headers include/lib${UPPER_LIB_NAME} include/lib${LIB_NAME} include
		)

		IF(NOT INC_DIR)
			MESSAGE("${LOG_PREFIX} ${LIB_NAME} library not found. ${LIB_NAME} features will be disabled.")
			LIST(APPEND WH_DEFS WH_${UPPER_LIB_NAME}_NOT_FOUND)
		ELSE()
			MESSAGE("${LOG_PREFIX} ${LIB_NAME} headers found!")

			FIND_LIBRARY(LIB_${LIB_NAME}
				NAMES ${LIB_NAME_ALTS}
				PATH_SUFFIXES Lib lib
			)

			IF(NOT LIB_${LIB_NAME})
				# TODO download

				FIND_LIBRARY(LIB_${LIB_NAME}
					NAMES ${LIB_NAME_ALTS}
				)
			ENDIF()

			IF(NOT LIB_${LIB_NAME})
				MESSAGE(WARNING "${LOG_PREFIX} ${LIB_NAME} library not found. ${LIB_NAME} features will be disabled.")

				SET("WH_${UPPER_LIB_NAME}_NOT_FOUND" TRUE PARENT_SCOPE)
				LIST(APPEND WH_DEFS "WH_${UPPER_LIB_NAME}_NOT_FOUND")
			ELSE()
				LIST(APPEND C_SOURCES ${${UPPER_LIB_NAME}_SOURCES})
				LIST(APPEND WH_LIBS ${LIB_${LIB_NAME}})
				LIST(APPEND WH_INCLUDES ${INC_DIR})
			ENDIF()
		ENDIF ()
	ENDIF()

	SET(C_SOURCES		${C_SOURCES}	PARENT_SCOPE)
	SET(WH_LIBS			${WH_LIBS}		PARENT_SCOPE)
	SET(WH_DEFS			${WH_DEFS}		PARENT_SCOPE)
	SET(WH_INCLUDES	${WH_INCLUDES}	PARENT_SCOPE)
ENDFUNCTION()
