INCLUDE(CheckIncludeFile)

SET(LIBRARY_NAMES vulkan Vulkan vulkan-1)

CHECK_INCLUDE_FILE("vulkan/vulkan.h" HAVE_VULKAN_HEADER)

IF(NOT HAVE_VULKAN_HEADER)
	MESSAGE(WARNING "Vulkan header not found. Vulkan features will be disabled.")
	ADD_COMPILE_DEFINITIONS(WH_VULKAN_NOT_FOUND=1)
ELSE()
	MESSAGE("Vulkan headers found!")

	FIND_LIBRARY(LIB_VULKAN
		NAMES ${LIBRARY_NAMES}
		HINTS ENV VULKAN_SDK
		PATH_SUFFIXES Lib lib
	)

	IF(NOT LIB_VULKAN)
		# TODO download

		FIND_LIBRARY(LIB_VULKAN 
			NAMES ${LIBRARY_NAMES}
		)
	ENDIF()

	IF(NOT LIB_VULKAN)
		MESSAGE(WARNING "Vulkan library not found. Vulkan features will be disabled.")
		TARGET_COMPILE_DEFINITIONS(${APP_NAME} PRIVATE WH_VULKAN_NOT_FOUND=1)
	ELSE()
		TARGET_LINK_LIBRARIES(${APP_NAME} INTERFACE ${LIB_VULKAN})
		LIST(APPEND C_SOURCES ${VULKAN_SOURCES})
	ENDIF()
ENDIF()
