INCLUDE(${CMAKE_CURRENT_LIST_DIR}/find.cmake)

WH_FIND_V2(
	"glfw"
	"glfw;glfw3;GLFW3"
	"glfw.h;glfw3.h;glfw3.h"
	"GLFW;glfw"
	FALSE
	WH_GLFW_LIB 
	WH_GLFW_INC
)

IF(WH_GLFW_LIB)
	MESSAGE(STATUS "WH_LIBS = ${WH_LIBS}")

	LIST(APPEND WH_LIBS ${WH_GLFW_LIB})
	LIST(APPEND WH_INCLUDES ${WH_GLFW_INC})
	LIST(APPEND C_SOURCES ${GLFW_SOURCES})
ELSE()
	LIST(APPEND WH_DEFS "WH_GLFW_NOT_FOUND")
ENDIF()
