INCLUDE(${CMAKE_CURRENT_LIST_DIR}/find.cmake)

#SET(LIB_NAME_ALTS )
#SET(LIB_HEADER_NAMES glew.h gl/glew.h GL/glew.h)
#WH_FIND_LIB(GLEW)

WH_FIND_V2(
	"GLEW"
	"glew;GLEW;glew32;glew32s"
	"glew.h"
	"GL;gl"
	FALSE 
	WH_GLEW_LIB 
	WH_GLEW_INC
)

IF(WH_GLEW_LIB)
	LIST(APPEND WH_LIBS ${WH_GLEW_LIB})
	LIST(APPEND WH_INCLUDES ${WH_GLEW_INC})
	LIST(APPEND GLEW_SOURCES ${C_SOURCES})
ELSE()
	LIST(APPEND WH_DEFS "WH_GLEW_NOT_FOUND")
ENDIF()
