SET(LIBRARY_NAME glew GLEW glew32 glew32s)

IF (NOT WIN32)
	FIND_LIBRARY(LIB_UNWIND NAMES ${LIBRARY_NAME} PATH_SUFFIXES Lib lib)

	IF (LIB_UNWIND)
		TARGET_LINK_LIBRARIES(${APP_NAME} INTERFACE ${LIB_UNWIND})
	ENDIF ()
ENDIF ()
