INCLUDE(CheckLanguage)

FUNCTION(ENABLE_LANGS)
	# Telling CMake that we use C and Fortran, Nasm
	# Adding Fortran Support
	CHECK_LANGUAGE(Fortran)
	CHECK_LANGUAGE(ASM_NASM)

	# Lets use the new C++ as well
	IF (NO_CXX_COMPILER)
		SET(CXX_ENABLED FALSE PARENT_SCOPE)
	ELSE()
		MESSAGE("${LOG_PREFIX} C++ is enabled")

		SET(CXX_ENABLED TRUE PARENT_SCOPE)
		SET(CMAKE_CXX_STANDARD 23 PARENT_SCOPE)
		SET(CMAKE_CXX_STANDARD_REQUIRED ON PARENT_SCOPE)
	ENDIF()

	IF(DEFINED CMAKE_ASM_NASM_COMPILER)
		MESSAGE("${LOG_PREFIX} NASM found: ${CMAKE_ASM_NASM_COMPILER}")
		SET(NASM_ENABLED FALSE PARENT_SCOPE)
	ELSE()
		SET(NASM_ENABLED TRUE PARENT_SCOPE)
		MESSAGE(STATUS "${LOG_PREFIX} NASM not found")
	ENDIF()

	# checking if we have Fortran on the system
	IF(CMAKE_C_COMPILER_ID MATCHES "TinyCC")
		MESSAGE(WARNING "${LOG_PREFIX} TCC Fortran turned off.")
		SET(FORTRAN_ENABLED FALSE PARENT_SCOPE)
	ELSEIF(CMAKE_Fortran_COMPILER)
		MESSAGE(STATUS "${LOG_PREFIX} Fortran compiler found: ${CMAKE_Fortran_COMPILER}")
		SET(FORTRAN_ENABLED TRUE PARENT_SCOPE)
	ELSE()
		MESSAGE(WARNING "${LOG_PREFIX} Fortran compiler NOT found. Falling back to C implementations.")
		SET(FORTRAN_ENABLED FALSE PARENT_SCOPE)
	ENDIF()
ENDFUNCTION()
