SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)

MESSAGE("\n\tWE ARE COMPILING FOR WINDOWS!")
MESSAGE(STATUS "-- Cross-compiling from Linux to Windows (MinGW)")

INCLUDE_DIRECTORIES(SYSTEM "${WINUX_SYSROOT}/include")
SET(CMAKE_LIBRARY_PATH "${CMAKE_LIBRARY_PATH};/opt/windows/lib")
SET(USE_FORTRAN OFF)
