
FUNCTION(OS_CONFIGURE)
	MESSAGE("\n\tWE ARE NOT ON WINDOWS!")

	IF (ANDROID OR CMAKE_SYSTEM_NAME STREQUAL "Android")
		MESSAGE(STATUS "Detected Android/Termux environment. Adding Termux prefix.")

		SET(TERMUX_PREFIX "/data/data/com.termux/files/usr")
		LIST(APPEND CMAKE_PREFIX_PATH ${TERMUX_PREFIX})
		LIST(APPEND CMAKE_INCLUDE_PATH "${TERMUX_PREFIX}/include")
		LIST(APPEND CMAKE_LIBRARY_PATH "${TERMUX_PREFIX}/lib")
	ENDIF()

	# checking if we have Fortran on the system
	IF(CMAKE_C_COMPILER_ID MATCHES "TinyCC")
		MESSAGE(WARNING "TCC Fortran turned off.")
		SET(USE_FORTRAN OFF)
	ELSEIF(CMAKE_Fortran_COMPILER)
		MESSAGE(STATUS "Fortran compiler found: ${CMAKE_Fortran_COMPILER}")
		ENABLE_LANGUAGE(Fortran)
		ADD_COMPILE_DEFINITIONS(WH_USE_FORTRAN=1)
		SET(USE_FORTRAN ON)
	ELSE()
		MESSAGE(WARNING "Fortran compiler NOT found. Falling back to C implementations.")
		SET(USE_FORTRAN OFF)
	ENDIF()
ENDFUNCTION()

FUNCTION(OS_COMPILE) 
	IF(CMAKE_C_COMPILER_ID MATCHES "TinyCC")
		TARGET_LINK_LIBRARIES(${APP_NAME} PRIVATE "m" "dl" "atomic" "bsd")
		TARGET_COMPILE_OPTIONS(${APP_NAME} PRIVATE
			${NON_MSVC_FLAGS}
			${COMPILER_O_LEVEL}
		)
	ELSE()
		IF(CMAKE_C_COMPILER_ID MATCHES "GNU")
			LIST(APPEND NON_MSVC_FLAGS -Wno-missing-field-initializers)
		ENDIF()

		TARGET_LINK_LIBRARIES(${APP_NAME} PRIVATE "m" "dl" "atomic" "bsd" "gcov")
		TARGET_COMPILE_OPTIONS(${APP_NAME} PRIVATE
			${NON_MSVC_FLAGS}
			${COMPILER_O_LEVEL}
		)
	ENDIF()
ENDFUNCTION()
