
FUNCTION(OS_CONFIGURE)
	MESSAGE("${LOG_PREFIX} WE ARE NOT ON WINDOWS!")
	SET(VULKAN_DISABLED FALSE PARENT_SCOPE)

	IF (ANDROID OR CMAKE_SYSTEM_NAME STREQUAL "Android")
		MESSAGE(STATUS "${LOG_PREFIX} Detected Android/Termux environment. Adding Termux prefix.")

		SET(TERMUX_PREFIX "/data/data/com.termux/files/usr" PARENT_SCOPE)
		SET(VULKAN_DISABLED TRUE PARENT_SCOPE)
		SET(IS_ANDROID TRUE PARENT_SCOPE)

		LIST(APPEND CMAKE_PREFIX_PATH ${TERMUX_PREFIX})
		LIST(APPEND CMAKE_INCLUDE_PATH "${TERMUX_PREFIX}/include")
		LIST(APPEND CMAKE_LIBRARY_PATH "${TERMUX_PREFIX}/lib")
	ENDIF()
ENDFUNCTION()

FUNCTION(OS_COMPILE) 
	SET(LIBS "m" "dl" "atomic")

	IF (NOT IS_ANDROID)
		LIST(APPEND LIBS "bsd")
	ENDIF()

	IF(CMAKE_C_COMPILER_ID MATCHES "TinyCC")
		MESSAGE("${LOG_PREFIX} TCC not gcov skipping it!")
	ELSE()
		IF(CMAKE_C_COMPILER_ID MATCHES "GNU")
			LIST(APPEND NON_MSVC_FLAGS -Wno-missing-field-initializers)
		ENDIF()

		IF (NOT ${IS_ANDROID})
			LIST(APPEND LIBS "gcov")
		ENDIF()
	ENDIF()

	TARGET_LINK_LIBRARIES(${APP_NAME} PRIVATE ${LIBS})
	TARGET_COMPILE_OPTIONS(${APP_NAME} PRIVATE
		${NON_MSVC_FLAGS}
		${COMPILER_O_LEVEL}
	)
ENDFUNCTION()
