
FUNCTION(OS_CONFIGURE)
	MESSAGE("${LOG_PREFIX} WE ARE ON WINDOWS!")

	# More Windows Magic for atomics :: Legacy KEEP
	IF (MSVC)
		MESSAGE("${LOG_PREFIX} NO ITS MSVC...")
		SET(CMAKE_C_STANDARD 17)
		SET(CMAKE_C_STANDARD ${CMAKE_C_STANDARD} PARENT_SCOPE)
		
		ADD_COMPILE_OPTIONS(
			$<$<C_COMPILER_ID:MSVC>:/experimental:c11atomics>
			$<$<C_COMPILER_ID:MSVC>:/Zc:preprocessor>
		)
	ENDIF()
ENDFUNCTION()

FUNCTION(OS_COMPILE) 
	TARGET_LINK_LIBRARIES(${APP_NAME} PRIVATE ntdll ${WH_LIBS})
	
	IF (MSVC)
		TARGET_COMPILE_OPTIONS(${APP_NAME} PRIVATE
			${MSVC_FLAGS}
		)
	ELSE()
		TARGET_COMPILE_OPTIONS(${APP_NAME} PRIVATE
			${NON_MSVC_FLAGS}
			--target=x86_64-pc-windows-gnu
			${COMPILER_O_LEVEL}
		)
	ENDIF()
ENDFUNCTION()
