#ifndef _wh_header_common_enum_
#define _wh_header_common_enum_

#include<wh-common/hacks.h>

enum {
	WH_STRUCT_TYPE_UNKOWN = 0,

	WH_TYPE_I64,
	WH_TYPE_U64,
	WH_TYPE_FLOAT,
	WH_TYPE_DOUBLE,
	WH_TYPE_BOOL,
	WH_TYPE_STRING,
	WH_TYPE_FUNCTION_PTR,

	WH_TYPE_ARRAY_I64,
	WH_TYPE_ARRAY_U64,
	WH_TYPE_ARRAY_FLOAT,
	WH_TYPE_ARRAY_STRING,

	WH_STRUCT_TYPE_INSTANCE,
	WH_STRUCT_TYPE_STRING,
	WH_STRUCT_TYPE_RGBA,
	WH_STRUCT_TYPE_BUFFER,

	// DO NOT MOVE LIST TYPES THIS ORDER IS IMPORTANT
	WH_STRUCT_TYPE_LLIST_SINGLE,
	WH_STRUCT_TYPE_LLIST_DOUBLE,
	WH_STRUCT_TYPE_LLIST_SYS_SINGLE,
	WH_STRUCT_TYPE_LLIST_SYS_DOUBLE,
	WH_STRUCT_TYPE_LLIST_STD_SINGLE, // will use malloc
	WH_STRUCT_TYPE_LLIST_STD_DOUBLE, // will use malloc
	// DO NOT MOVE LIST TYPES THIS ORDER IS IMPORTANT
	
	// DO NOT MOVE HASHMAP TYPES THIS ORDER IS IMPORTANT
	WH_STRUCT_TYPE_HASHMAP_LAZY_WOLF,
	WH_STRUCT_TYPE_HASHMAP_LAZY_SYS,
	WH_STRUCT_TYPE_HASHMAP_LAZY_STD,
	// DO NOT MOVE HASHMAP TYPES THIS ORDER IS IMPORTANT

	WH_STRUCT_TYPE_HEAP_ARENA,
	WH_STRUCT_TYPE_HEAP_BUCKET,
	WH_STRUCT_TYPE_HEAP_FREELIST,
	WH_STRUCT_TYPE_HEAP_STACK,
	WH_STRUCT_TYPE_HEAP_NODE,

	WH_STRUCT_TYPE_IMG_PNG,
	WH_STRUCT_TYPE_IMG_JPEG,

	WH_STRUCT_TYPE_ENUM_END
};

enum {
	WH_SUCCESS,
	WH_ERROR_UNKOWN,

	WH_ERROR_INVALID_PARAM,
	WH_ERROR_INVALID_PARAM_NULLPTR,
	WH_ERROR_FAILED_MEMREQ,
	WH_ERROR_HEAP_TOO_SMALL,
	WH_ERROR_NO_MATCH,
	WH_ERROR_NO_MEMORY,
	WH_ERROR_OVERFLOW_ISSUE,

	WH_ERROR_ENUM_END
};

#ifndef _WIN32
enum {
	STRUNCATE = 10000
};
#endif

#endif /* _wh_header_common_enum_ */
