INCLUDE(${CMAKE_CURRENT_LIST_DIR}/find.cmake)

WH_FIND_V2(
	"vulkan"
	"Vulkan;vulkan;vulkan-1"
	"vulkan/vulkan.h"
	""
	FALSE 
	WH_VULKAN_LIB 
	WH_VULKAN_INC
)

IF(WH_VULKAN_LIB)
	LIST(APPEND WH_LIBS ${WH_VULKAN_LIB})
	LIST(APPEND WH_INCLUDES ${WH_VULKAN_INC})
	LIST(APPEND C_SOURCES ${VULKAN_SOURCES})
	
	MESSAGE(STATUS "WH_LIBS = ${WH_LIBS}")
	LIST(APPEND WH_DEFS "WH_VULKAN_FOUND")
ENDIF()
