INCLUDE(${CMAKE_CURRENT_LIST_DIR}/find.cmake)

WH_FIND_V2(
	"GLEW"
	"glew;GLEW;glew32;glew32s"
	"glew.h"
	"GL;gl"
	FALSE 
	WH_GLEW_LIB 
	WH_GLEW_INC
)

IF(WH_GLEW_LIB)
	LIST(APPEND WH_LIBS ${WH_GLEW_LIB})
	LIST(APPEND WH_INCLUDES ${WH_GLEW_INC})
	LIST(APPEND C_SOURCES ${GLEW_SOURCES})

	MESSAGE(STATUS "WH_LIBS = ${WH_LIBS}")
	LIST(APPEND WH_DEFS "WH_GLEW_FOUND")
ENDIF()
